title: Marauder's Map
description: >
  Riddikulusly difficult Harry Potter trivia game, for Alexa and Google Home.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock